name: Stock Alert Scheduler

on:
  schedule:
    # 매일 평일 아침 9시 (UTC 0:00)에 TQQQ 알림 실행
    - cron: '0 0 * * 1-5'
    # 매일 평일 저녁 5시 (UTC 8:00)에 코스피 검색기 실행
    - cron: '0 8 * * 1-5'
    # 테스트용: 오늘 저녁 9시 20분에 코스피 검색기만 실행 (UTC 12:20)
    - cron: '20 12 * * *'
  workflow_dispatch:  # 수동 실행 옵션

jobs:
  run_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r telebot/requirements.txt

      - name: Set environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          KOSPI_TELEGRAM_BOT_TOKEN: ${{ secrets.KOSPI_TELEGRAM_BOT_TOKEN }}
          KOSPI_TELEGRAM_CHAT_ID: ${{ secrets.KOSPI_TELEGRAM_CHAT_ID }}
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> $GITHUB_ENV
          echo "KOSPI_TELEGRAM_BOT_TOKEN=$KOSPI_TELEGRAM_BOT_TOKEN" >> $GITHUB_ENV
          echo "KOSPI_TELEGRAM_CHAT_ID=$KOSPI_TELEGRAM_CHAT_ID" >> $GITHUB_ENV

      # TQQQ 알림 (아침 9시)
      - name: Run TQQQ alerts (UTC 0:00, KST 9:00)
        if: github.event.schedule == '0 0 * * 1-5'
        run: |
          cd telebot
          python -m main --run tqqq

      # 코스피/코스닥 검색기 (저녁 5시)
      - name: Run KOSPI Stock Scanner (UTC 8:00, KST 17:00)
        if: github.event.schedule == '0 8 * * 1-5'
        run: |
          cd telebot
          python -m main --run potential
          python -m main --run wave

      # 테스트용 - 오늘 저녁 9시 20분에 코스피 검색기만 실행
      - name: Test KOSPI Scanner Only (UTC 12:20, KST 21:20)
        if: github.event.schedule == '20 12 * * *' || github.event_name == 'workflow_dispatch'
        run: |
          cd telebot
          python -m main --run potential
          python -m main --run wave

      # 수동 실행 시 모든 기능 테스트
      - name: Run All Functions (Manual Trigger Only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd telebot
          python -m main --run all 